### ISSUE TITLE
Some feedback and suggestions on mod issues

### ISSUE THREAD

**Issue by c469591** [khanshoaib3/stardew-access#103]
Some feedback and suggestions on mod issues

Hello, I just played shortly and found some problems with this mod, as well as some of my thoughts.
I will organize the problems and write down →

1. in the main menu of the game (Co-op Button), after I select the host option
I pressed s to go down, I could see the name of the farm I created before, for example, the farm of Lamb, and then pressed a few more times, I could hear the refresh.
But when I press w to go up, I can only hear the new farm, but I can't find the Lamb farm.
1. When I want to join someone else's farm, I select
Join lan game
After I input the other party's ip and confirm, I can press w or s to see the other party's farm, but it's not very stable.
Sometimes I can hear the farm name, sometimes he will say blank.
I need to press d to the right, and then press ctrl+enter to join the game.
But then he wouldn't read aloud what the button was when he went to the right, so I guessed that would be the join button.
After joining the game, I pressed any button without any response, and then I don't know what I pressed, but I pressed the left and right buttons to see the options that let me enter the name of the farmer, the things I like, and so on.
1. many places where there is a back button are not read aloud, such as in the option to choose which archive to load, or in the multiplayer option and in the dialog box to enter IP.
He would only read the blanks aloud, but I wasn't sure what the blanks were.
I use ocr software, only to find that the above is actually the back button
1. The game itself supports Chinese, but after I switched to Chinese, there are still a lot of things he will read aloud in English when I use the mod to play the game.
For example, grass, water and other objects.
This mod has a translation file inside? This mod is read aloud the text in the game, or through the mod inside a file to read aloud the text?
If the instructions are to modify a simple text file, perhaps it can help with the Chinese translation.
I am very confused why the game has been switched to Chinese, but the output content will still have English.
And it is not very stable, sometimes something will become English, sometimes it will become Chinese again, I am talking about when reading aloud through the screen reader software

All in all, this mod is still great and I hope it can do better, thanks!

**Comment by khanshoaib3** [comment]
Looks like the co-op menu patches have bug, will look into these and thanks for the description of bugs, it'll help in recreating them :) 
The mod uses the game provided translations for stuff like items but some of them don't have any translations like grass or water. We would either have to hardcode the translations for such items in or wait for the next update to the game itself which I heard will fix this, I may be wrong though. And as for the features introduced in this mod, a part of it is already translated but a majority isn't at the moment. The next to next update will be focused on translating the mod, so stay tuned! And you can find the translations files [here](https://github.com/khanshoaib3/stardew-access/tree/master/stardew-access/i18n).

Thanks you for the feedback!

**Comment by khanshoaib3** [comment]
All of the issues have been addressed :), so closing this...
