### ISSUE TITLE
Unable to build with snap mouse

### ISSUE THREAD

**Issue by GrowingInTheRain** [khanshoaib3/stardew-access#109]
While in the building screen (making a coop or whatever) the locked mouse makes you entirely unable to move the cursor, even with the inbuilt cursor moving keys or trackpad.

Suggested fixes:
- Check for building screen and disable snap mouse in that (similar to in menus)
- Add a hotkey to toggle mouse snapping

**Comment by khanshoaib3** [comment]
There is already a command to disable it so I think it would be better to disable it in the building screen.
Although I think you would also need to disable force gamepad mode to be able to use mouse in that screen.
Alternatively, you can use commands to mark a tile and use it in the building menu, here's a guide - [here](https://github.com/khanshoaib3/stardew-access/wiki/4-Guides#farm-building-related)

**Comment by khanshoaib3** [comment]
Turns out, snap mouse is not the issue here, having the gamepad mode to force on is what's causing the trouble.
So I suggest set gamepad mode to force off before going to that menu.
