### ISSUE TITLE
How to use CommunityCenter Quick Keys

### ISSUE THREAD

**Issue by c469591** [khanshoaib3/stardew-access#110]
Hello, I don't quite understand how to use CommunityCenter's Quick Keys.
I can press c, v, i to view it.
But if I have an item that I need for a mission, how do I put it in the input?
There is a mission that requires 99 wood, should I organize the 99 wood in my backpack first, or can I just pull the items into the input?
Please tell me the detailed steps, because I have tried all kinds of methods, using the left mouse button or right mouse button, but nothing works.
Thank you!

**Comment by khanshoaib3** [comment]
First we use c to cycle through the backpack items and select the item to donate with [ or left mouse button.
Then use v to cycle through the input slots and place the item in one of the empty slot with [ or left mouse button.
In one of the bundles you would have to purchase instead of donate, you can use p to snap to the purchase button and then press [ or left mouse button.

**Comment by c469591** [comment]
Thank you for the explanation. I did the same thing too. However, after selecting the task items in my backpack, I clicked the left mouse button in the input slot, but there was no response or sound effect. When I pressed 'V' to check, it still showed as 'input', indicating that I have not successfully placed the items in. I am currently working on the Spring Collection Pack. Could it be that there is a conflict with the MOD that I have installed?

**Comment by c469591** [comment]
Additionally, I have a question: How can animal stores purchase animals? When I found the option for buying a chicken and clicked on it, a selection prompt appeared asking where to place the chicken coop, but I was unable to make a purchase because no keys provided a response. Could you tell me what I should do? Thank you!

**Comment by khanshoaib3** [comment]
> Thank you for the explanation. I did the same thing too. However, after selecting the task items in my backpack, I clicked the left mouse button in the input slot, but there was no response or sound effect. When I pressed 'V' to check, it still showed as 'input', indicating that I have not successfully placed the items in. I am currently working on the Spring Collection Pack. Could it be that there is a conflict with the MOD that I have installed?

Could be, send the log file, that'll help finding out the issue.

**Comment by c469591** [comment]
I see, thank you very much.
I later found out that the community center tasks must be operated properly by going to the community center.
The community center operation from the backpack is not valid.
Anyway, I can now successfully complete the task, thank you again for your patient explanation

**Comment by c469591** [comment]
I have another question that I'd like to ask. 
In multiplayer mode, where can I find everyone's mailbox? I can only find my own at the location 68.16, but others can't seem to find theirs. When they interact with the mailbox at 68.16, the game tells them it's not their mailbox. 
I also checked the official wiki and found a command to use in SMAPI to search for mailboxes, but when I tried inputting "doesitemexist mail," it said there was no such command. I'm not sure if I typed it incorrectly or if there is another correct syntax. 
Is there a faster way to locate NPCs, doors, and other interactive objects on the map? 
Actually, I've been wanting to improve the accessibility MOD's game help wiki, but unfortunately English is not my native language. Thank you!

**Comment by khanshoaib3** [comment]
That's a known issue, we'll be working on it soon but it will probably be fixed in next update.

**Comment by c469591** [comment]
Do you mean about the mail box problem, this is a bug?

**Comment by khanshoaib3** [comment]
Yeah, the mod does not detect the mail boxes of cabins.
