### ISSUE TITLE
[refactor] Code Organisation

### ISSUE THREAD

**Issue by khanshoaib3** [khanshoaib3/stardew-access#112]
Organize code in HarmonyPatches.cs and CustomCommands.cs

**Comment by ParadoxiKat** [comment]
+ refactor Features/Utils.cs.  Contains code to open json files, handle color matching, and some enums. Enums should have their own files in Features; other classes should be moved to new `Utils` namespace (utils/ColorMatcher.cs etc)

**Comment by khanshoaib3** [comment]
#92 <- done

**Comment by khanshoaib3** [comment]
Organize the custom commands the same way as patches i.e., create an `ICustomCommand` interface with `Add()` method and a `CustomCommandManager` class that adds all the custom commands.

**Comment by khanshoaib3** [comment]
Maybe replace `AccessTools.Method()` with `AccessTools.DeclaredMethod` and use name of the method as string instead of using `nameof()`.
