### ISSUE TITLE
mod will lock the mouse

### ISSUE THREAD

**Issue by c469591** [khanshoaib3/stardew-access#114]
Hello.
Is it possible to leave the Stardew Valley window without locking the mouse?
I find that I can't move my mouse on other software when the game is running.
Thanks!

**Comment by khanshoaib3** [comment]
You can open a menu to temporarily disable the snap mouse feature.
Also, you can enter the `snapmouse` command to manually disable/enable it.

**Comment by c469591** [comment]
ok, thank you
