### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by Rizumu85** [khanshoaib3/stardew-access#116]
I have translated the static-tiles to Chinese but I am not sure if there is more text to be translated?

**Comment by Rizumu85** [comment]
Oh I just saw the update from 2 days ago, so my question now will be: By translating all the files in the assets folder should that be enough to make it work?
![image](https://github.com/khanshoaib3/stardew-access/assets/25150828/22beafed-0c1b-42d0-a1a9-f0f153774115)

**Comment by khanshoaib3** [comment]
It should be, I think.
The next update (or the one after that) will be focused on the translation.
So maybe wait till that, for now, translating these files should be enough.
There may be some bugs though.

**Comment by khanshoaib3** [comment]
#39

**Comment by khanshoaib3** [comment]
This issue is moved to #39

**Comment by khanshoaib3** [comment]
Hi @Rizumu85, so we are currently working on translating the entire mod, so far, the mod has been partially internationalized. Are you up for translating it to Chinese 🙂? Just note that the project now uses project fluent for translations which is more powerful than the regular json method of translation hence might be more (or less) complicated.

**Comment by Rizumu85** [comment]
> Hi @Rizumu85, so we are currently working on translating the entire mod, so far, the mod has been partially internationalized. Are you up for translating it to Chinese 🙂? Just note that the project now uses project fluent for translations which is more powerful than the regular json method of translation hence might be more (or less) complicated.

Yes I am still interested in making the translation in Chinese, let me check that out, and thank you for reminding me.

**Comment by Rizumu85** [comment]
> Hi @Rizumu85, so we are currently working on translating the entire mod, so far, the mod has been partially internationalized. Are you up for translating it to Chinese 🙂? Just note that the project now uses project fluent for translations which is more powerful than the regular json method of translation hence might be more (or less) complicated.

Emm, I have looked around but I can’t quite get where I can access the project fluent, could you show me where to access it?

**Comment by khanshoaib3** [comment]
> > Hi @Rizumu85, so we are currently working on translating the entire mod, so far, the mod has been partially internationalized. Are you up for translating it to Chinese 🙂? Just note that the project now uses project fluent for translations which is more powerful than the regular json method of translation hence might be more (or less) complicated.
> 
> Emm, I have looked around but I can’t quite get where I can access the project fluent, could you show me where to access it?

So the file that you should translate is `en.ftl` which should be inside the `i18n` folder. Also, because we use project fluent now, I suggest you make a translation mod for Chinese and upload it to nexus, it will give you the credit for translation and you can update the translations when the mod updates, plus I won't have to worry about updating translations for languages I don't speak before releasing a new version of the mod 🙂.

**Comment by Rizumu85** [comment]
> > > Hi @Rizumu85, so we are currently working on translating the entire mod, so far, the mod has been partially internationalized. Are you up for translating it to Chinese 🙂? Just note that the project now uses project fluent for translations which is more powerful than the regular json method of translation hence might be more (or less) complicated.
> > 
> > 
> > Emm, I have looked around but I can’t quite get where I can access the project fluent, could you show me where to access it?
> 
> So the file that you should translate is `en.ftl` which should be inside the `i18n` folder. Also, because we use project fluent now, I suggest you make a translation mod for Chinese and upload it to nexus, it will give you the credit for translation and you can update the translations when the mod updates, plus I won't have to worry about updating translations for languages I don't speak before releasing a new version of the mod 🙂.

Okok thank you for the explanation and your suggestions, I will do that!

**Comment by khanshoaib3** [comment]
Awesome! You can follow the [fluent documentation]() and contact me here or on discord in case you need any help :)
I'll reopen the issue for now.

**Comment by boholder** [comment]
Hi @Rizumu85 , sorry for bothering, have you working on this? There is someone who is willing to help translate the text, but he/she doesn't have the development skills, so I'm wondering if you could help make and upload the translation mod base on finished `*ftl` files, if you don't have the time to translate it? He/she can chat with you via QQ, if you want.

**All** the files in this directory need be translated.
https://github.com/khanshoaib3/stardew-access/tree/master/stardew-access/i18n

**Comment by khanshoaib3** [comment]
Just wanted ya'll know that I'll be making a template repo for the i18n content pack that you'll have to make.
I'll probably announce it today itself and also, get the `*ftl` files from the beta rather directly from the repo.

**Comment by boholder** [comment]
> Just wanted ya'll know that I'll be making a template repo for the i18n content pack that you'll have to make. I'll probably announce it today itself and also, get the `*ftl` files from the beta rather directly from the repo.

I... personally don't recommend separating the i18n content from the code, I felt a bit strange updating two projects at the same time when I was coding mine-access. You can use git tags to mark the version, and follow the tags to find the correct version of the waiting-for-translation files. 😀

**Comment by Rizumu85** [comment]
Hey I started a little but didn’t have time to finish it, I will be able to chat with her via QQ if she wants. Where should I post my QQ?
2023年10月21日 -0500 AM2:14 boholder ***@***.***>，写道：

**Comment by khanshoaib3** [comment]
Here's the template repo I was talking about earlier, [this](https://github.com/darkade-games/stardew-access-i18n/)

**Comment by boholder** [comment]
> Hey I started a little but didn’t have time to finish it, I will be able to chat with her via QQ if she wants. Where should I post my QQ?

Hi, here is **his** [QQ](https://example.com/2027971726) (I didn't find your email and I think it's a littile bit inappropriate to public his QQ, I'll delete this reply when you get in touch with him...)

**Comment by boholder** [comment]
> Hello, I want to translate Chinese, but I do not know how to achieve it, so I am very entangled in the choice

He is the one I'm talking about ☝️ Welcome to GitHub!

**Comment by khanshoaib3** [comment]
> He is the one I'm talking about ☝️ Welcome to GitHub!

Cool! I'll assign him this issue as well.

**Comment by wu2002jian** [comment]
@khanshoaib3 thank you

**Comment by wu2002jian** [comment]
> @khanshoaib3 thank you

what should I do

**Comment by Rizumu85** [comment]
> Here's the template repo I was talking about earlier, [this](https://github.com/darkade-games/stardew-access-i18n/)

Thank you I will check it out

**Comment by c469591** [comment]
May I ask if the Chinese translation has come to a halt? I'm still not seeing any Chinese with the latest 1.5rc version. I can also participate in the translation work, but what puzzles me is whether I should submit a PR directly here after completing my translations?

**Comment by khanshoaib3** [comment]
Sorry for responding late @c469591 

I believe that the work for the Chinese translation was completed, it was in the testing stages. (Right? @Rizumu85 and @wu2002jian)

But since you have completed the translations, you can create the translation mod.
Actually, we want the main mod to have only the English translation because with the help of Project Fluent we can create translation mods for a mod.
Which also means there can be more than one translations for a single language.
You can refer to [this](https://github.com/darkade-games/stardew-access-i18n/) repo for the info on how to create such mod.

**Comment by c469591** [comment]
Hello, so do you mean that someone has already completed it or is there some other meaning? I didn't quite understand. Here, I have finished the task, but found that there are still many contents that cannot be translated. Those contents did not appear in the English translation template, such as the names of buildings.

**Comment by Rizumu85** [comment]
> Hello, so do you mean that someone has already completed it or is there some other meaning? I didn't quite understand. Here, I have finished the task, but found that there are still many contents that cannot be translated. Those contents did not appear in the English translation template, such as the names of buildings.

Hey, yes we already finish the chinese translation but I haven't got the time to post the files. For somethings that still remain in English and can't be translated, khanshoaib3 showed me to use code to translate those, so that is something we have missing too. If you want you can join us and work with us about that, I will dm me QQ so we can talk about it.

**Comment by Rizumu85** [comment]
> Hello, so do you mean that someone has already completed it or is there some other meaning? I didn't quite understand. Here, I have finished the task, but found that there are still many contents that cannot be translated. Those contents did not appear in the English translation template, such as the names of buildings.

Ok I forgot that I can't dm in github, Add my QQ here 3094401197 and let me know when you do so I will delete this comment.

**Comment by c469591** [comment]
You've been added as a friend!

**Comment by geblni** [comment]
Hello, how is the project in Chinese going? Where can I find the Chinese language support files? Thank you.

**Comment by Rizumu85** [comment]
We still have it testing over this QQ group, if you need the current version please take a look we have the files here. 551583184

**Comment by geblni** [comment]
> We still have it testing over this QQ group, if you need the current version please take a look we have the files here. 551583184
> On Mar 20, 2024, 4:01 AM -0500, geblni ***@***.***>, wrote:
> > Hello, how is the project in Chinese going? Where can I find the Chinese language support files? Thank you.
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you were mentioned.Message ID: ***@***.***>
> 

Hello, is the number you sent a QQ number or a group number? I have already applied to be friends, but I don't know if it's you.

**Comment by Rizumu85** [comment]
is a group QQ number

**Comment by geblni** [comment]
Excuse me, I've tried searching for this group number, but still couldn't find it. Could you please double-check if the group number is correct? Also, is the group open? @

**Comment by Rizumu85** [comment]
maybe try this qr code

**Comment by Rizumu85** [comment]
![qrcode_1711078679977](https://github.com/khanshoaib3/stardew-access/assets/25150828/3935a10a-780c-4df1-a13d-0178f374b353)
Try this qr code

**Comment by Rizumu85** [comment]
> Excuse me, I've tried searching for this group number, but still couldn't find it. Could you please double-check if the group number is correct? Also, is the group open? @

I have posted a qr code, try that one

**Comment by Rizumu85** [comment]
https://www.nexusmods.com/stardewvalley/mods/21784
@khanshoaib3 We just released the translation over Nexus Mods

**Comment by khanshoaib3** [comment]
Awesome! I'll close this issue then. Thank you guys for the hard work :heart:
