### ISSUE TITLE
Bugs in the latest Stardew Access for MacOS

### ISSUE THREAD

**Issue by fz0308** [khanshoaib3/stardew-access#120]
Hello, thanks for making this mod works in MacOS. However, I found at least 2 bugs when I play Stardew Valley using Stardew Access on MacOS. First, several texts, like chat and intro can't be read. And second, I was pressed left control+space in character creation menu, but nothing happens. Please fix these 2 bugs. Thanks before

**Comment by khanshoaib3** [comment]
@fz0308 send the log file please, It'll help find the cause easier :)
And try to remap the left control + spacebar to something else and see if it works or not.

**Comment by fz0308** [comment]
Ok, I can enable the character creation design menu without changing anything. Press control+command+space, but where I can find the log file?

**Comment by khanshoaib3** [comment]
You can find the log at `~/.config/StardewValley/ErrorLogs`.
Additionally, instead of sending the log file here directly, parse the log on the [SMAPI log parser](https://smapi.io/log/) and send the generated link.

**Comment by fz0308** [comment]
@khanshoaib3
https://smapi.io/log/b9906052588f44948becdc0d9f051c11
And I want to report a bug again. I can't donate an item to ghunter using C button. I am not sure this is also happen in community but this is really annoying

**Comment by khanshoaib3** [comment]
@fz0308 There were no error related to the donation menu, can you regenerate the issue and then send the log file.
Also the auto tool select mod is broken.
