### ISSUE TITLE
strange behavior after going over a certain amount of artifacts donated to the museum

### ISSUE THREAD

**Issue by lilmike** [khanshoaib3/stardew-access#126]
Hiya,

In both a multiplayer save and a solo save that I've been running, once the museum gets to a certain number of donated items, upon trying to donate an item will cause speech to speak the tile name/number, and immediately send a blank string after, thus making speech make more of a tsk sound. Once this starts happening, it is impossible to place the artifact or mineral onto a tile. Any idea why this is happeningg? I can try and see what the number is or any other details if needed.

Thanks!

-Michael.

**Comment by lilmike** [comment]
On initial assessment, it looks like after donating 10 items to the museum, the cursor becomes stuck at x28 y15 with no ability to move the cursor possible. It is also the case that the game starts to speak the slot, then immediately sends a blank message, canceling speech. I'm not sure how to get my cursor to move from this apparently filled tile onto one I can use. Any help is appreciated.

-Michael.

**Comment by khanshoaib3** [comment]
Try using the [primary info key](https://github.com/khanshoaib3/stardew-access/blob/master/docs/keybindings.md#primary-info-key) to donate the artifact automatically to an empty tile.

**Comment by lilmike** [comment]
Thank you. That helps alot.

-Michael.





On Mon, Jun 19, 2023 at 07:26:01AM -0700, Mohammad Shoaib Khan wrote:
>Try using the [primary info key](https://github.com/khanshoaib3/stardew-access/blob/master/docs/keybindings.md#primary-info-key) to donate the artifact automatically to an empty tile.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/khanshoaib3/stardew-access/issues/126#issuecomment-1597287880
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my bedside...
stationary bicycle
