### ISSUE TITLE
Merge GridMovement and ObjectTracker Features from AccessibleTiles

### ISSUE THREAD

**Issue by ParadoxiKat** [khanshoaib3/stardew-access#131]
This has been a work in progress; the recent refactoring PR was a major part of the groundwork for it. I'm testing / fixing the GridMovement Feature now; having a place to track progress and issues will be useful. Feel free to assign it to me.

**Comment by ParadoxiKat** [comment]
Updated and rebased to include work done in i18n branch. Preparing to migrate in ObjectTracker.

**Comment by ParadoxiKat** [comment]
GridMovement and ObjectTracker features have been merged. It needs work; there's likely a lot of overlapping code that can be refactored and optimized. ObjectTracker could use tighter integration with Radar and Dynamic/Static tiles, for example. But it works at least as well as the last AccessibleTiles Beta. Likely a few hidden bugs.

**Comment by khanshoaib3** [comment]
@ParadoxiKat Bug/Feature request #156

**Comment by ParadoxiKat** [comment]
ff1eacf94d2d95bdc1f17e3985ef7953f8928629 implements a new `AccessibleTile` subsystem, meant to replace the functionality of SpecialPoints (from AccessibleTiles the mod) and stardew-access' `TileInfo`, `DynamicTiles`, `StaticTiles`, and similar tile/object info gathering functions.

It is broken down into 4 main components:
1. `AccessibleTile`: this class represents a single tile on the map and all it's interesting (to us) details. It can be made aware of conditions that mean it should or shouldn't be represented in the object tracker, including whether or not specific mods are loaded.
2. `AccessibleLocation`: This class acts as a container of `AccessibleTiles`, managing a particular location's points of interest. It has methods for querying particular points for their tile or finding groups of tiles by type. Can also be made aware of show/hide conditions and be dependent on specific mods.
3. `AccessibleTileHelpers`: holds the conditional functions tiles and locations can rely on as well as a register method other mods could use to register a new condition handler.
4. `AccessibleTileManager`: The singleton class most of the code will interact with. Has methods for looking up particular locations or operating directly on the current location. Is responsible for loading the `tiles.json` file which holds tile configuration info. This file will replace `static-tiles.json`.

**Comment by ParadoxiKat** [comment]
97ae37a248b61b1524f75bf562b5f2d79747ab39 Added ability for location entries in tiles.json to represent multiple locations via comma separated names.

**Comment by ParadoxiKat** [comment]
63c0510f4c8ae85e0ffd084f77187991605199f7 Removed static-tiles.json in favor of tiles.json. Can be overridden by user in tiles_user.json.
The primary difference is that each location is now an array of objects rather than an object itself, and the tile's name/translation key is now an entry in the object.
Example:
Old format:
```
  "farm": {
    "static_tile-farm-lumber_pile": {
      "x": [60, 61],
      "y": [14],
      "type": "decoration"
    }
  },
```

New format:
```
  "Farm": [
    {
      "NameOrTranslationKey": "static_tile-farm-lumber_pile",
      "X": [60, 61],
      "Y": [14],
      "Category": "decoration"
    }
  ],
```
However, the new format supports additional entries as well, such as:
1. "DynamicNameOrTranslationKey": name of a function which accepts an `AccessibleTile` instance and returns the calculated name to speak instead of a static string provided by "NameOrTranslationKey".
2. "DynamicCoordinates": name of a function, accepting `AccessibleTile` and returning a `Vector2`; to be used in place of providing static "X" and "Y" values.
3. "WithMods": list of string names of required mods; if names are present and corresponding mods are not loaded this entry will not be loaded.
4. "Conditions": list of names of functions accepting `AccessibleTile` or `AccessibleLocation and returning true or false. If any conditions are present, they must all return true for the tile or location to be shown. Conditions may include arguments separated by a `:`. Arguments will be found in the instance's `ConditionArgs` dict.
5. `IsEvent`: bool indicating if this is event specific.
6. `"IslocationSettings": bool indicating whether or not this entry applies to the location rather than to a tile. Only "WithMods", "Conditions" and "IsEvent" are valid here. When multiple such entries are found, subsequent entries update rather than overwrite previous ones.

**Comment by ParadoxiKat** [comment]
c0d9f140d4c7d5920c3f9676fb924180884b08be implements using the tiles_user.json when present

**Comment by ParadoxiKat** [comment]
c0fce86c4245a57288c30d4184368956b51fc126 automatically convert user's old custom-tiles.json to new tiles_user.json

**Comment by ParadoxiKat** [comment]
19a0b8c1c393607d980b40323002d78be02b02d0 and 69ef0c8763d9675a854f14f89e0aecc0322adabf add and implement several conditional functions:

1. "Farm": returns true or false if the supplied name matches a particular farm. E.G. `"Conditions": ["Farm:forest"]` will only match the forest farm.
2. "FarmHouse": used to match above a specific farm house upgrade. E.G. `"Conditions": ["Farmhouse:3"]` only matches the fully upgraded farm house. A value of 2 would match both level 2 and 3. A value of 1 would work but would be pointless.
3. "HasQuest": Matches if the player has a particular quest. E.G. `"Conditions": ["HasQuest:5"]` will be true if the user has completed the quest with id 5.
4. "JojaMember": true if the player is on the Joja route. E.G. `"Conditions": ["JojaMember"]`

**Comment by ParadoxiKat** [comment]
b8b489087d553e5ecb25b5139c00dff36befa3ce update GridMovement to calculate speed taking player speed modifiers into account such as walking vs running and speed boosts.
Added 3 new config options to fine tune GridMovement:
1. `GridMovementSpeed`: from 0 to 100, determines how slow or fast the user moves relative to normal game speed. A value of 100 is approximately the same as normal game speed.
2. `GridMovementTilesPerStep`: whether or not you hear one step for every tile crossed. Defaults to 1 meaning a step for every tile. A value of two would play a step every other tile without actually slowing down movement.
3. `GridMovementDelayAfterDirectionChange`: how long to delay between initially pressing the key and beginning to move. Without this and `GridMovementSpeed` set very low, the time between pressing the key and initiating walking is the same as the time between the first step and the next. A low value would allow for moving rapidly by rapidly tapping the key without engaging the between-step delay.

**Comment by ParadoxiKat** [comment]
513bc292b4f8cf0c15ea1a1299960dc7b8037e5f readd the fishing locations from AccessibleTiles along with new dedicated fishing category.
