### ISSUE TITLE
an error while trying to use the beta, renders the mod unusable.

### ISSUE THREAD

**Issue by paxcoder** [khanshoaib3/stardew-access#144]
Hi.
when I open the game I hear capital I.
then when it loads: I hear: capital n.
when scroll through options, I don't hear anything more than one letter.

**Comment by Flameborn** [comment]
Hi,

This has been fixed today via https://github.com/khanshoaib3/stardew-access/pull/143

**Comment by paxcoder** [comment]
the beta is really stable now.
