### ISSUE TITLE
I can't donate stuff to Gunter sometimes.

### ISSUE THREAD

**Issue by paxcoder** [khanshoaib3/stardew-access#153]
Hi.
sometimes it works, sometimes not.

**Comment by khanshoaib3** [comment]
Can't really help much without a log file 🙂

**Comment by paxcoder** [comment]
Ok, I can tell you if I use C, it donates, but when I’m pressing left bracket, it doesn’t work, it tells me the slots, I press [ again, it does, nothing.

**Comment by khanshoaib3** [comment]
Oh it's not a bug, to donate, traditionally we have to select the item with left mouse click i.e., left bracket and then find a empty slot and then press left bracket again.
But this is kinda buggy so I added a helper C keybind that automatically finds an empty spot and places the item.
Hope this clarifies the issue :)

**Comment by paxcoder** [comment]
Ok, but it wasn’t documented in the change log.

**Comment by Flameborn** [comment]
If you mean the commit logs, you will find that the documentation is a better source to summarize commands and key bindings. In particular, https://github.com/khanshoaib3/stardew-access/blob/master/docs/keybindings.md under the *Primary Info Key* heading.

**Comment by paxcoder** [comment]
Nope, I mean beta change logs.
