### ISSUE TITLE
beta version is not showing fishing spots

### ISSUE THREAD

**Issue by lilmike** [khanshoaib3/stardew-access#154]
Hiya,

The latest beta of stardew access with accessible tiles built in is no longer showing  fishing spots as a place to move to. This feature would be nice to bring back. Thanks!

-Michael.

**Comment by ParadoxiKat** [comment]
Fixed by 513bc292b4f8cf0c15ea1a1299960dc7b8037e5f available in v1.5.0-beta.2.
