### ISSUE TITLE
using the c key to navigate the crafting menu skips some crafting recipes

### ISSUE THREAD

**Issue by lilmike** [khanshoaib3/stardew-access#158]
Hiya,

I've got level 8 mining and foraging, level 9 farming, level 10 fishing, and level 7 combat, plus several unlockable recipes. I've noticed that on page two and beyond of the crafting list, using the c key to go through the recipes skips a row or two at the bottom. For example, I needed to craft two mega bombs for a fish pond, and it turned out that recipe was on the second page, but using the c key to go through the list just never got to the row containing mega bomb and several other recipes. If this could be fixed, that would be great, as I apparently have several recipes I didn't even know I had, and navigating the list with the wasd keys is kind of inconsistant.

-Michael.

**Comment by khanshoaib3** [comment]
Sorry for the late reply, I thought I had already replied to this lol.

The c key is supposed to cycle through the recipes that are currently displayed so it won't be able to detect recipes from other pages.
I guess a possible solution for this would be to also add the previous and next page buttons to the c key.

**Comment by lilmike** [comment]
Hiya,

So I know about the other pages, but the problem I'm having is that
there are actually recipes on the current page that the c key is not
cycling through.

-Michael.






On Sat, Sep 02, 2023 at 06:41:17AM -0700, Mohammad Shoaib Khan wrote:
>Sorry for the late reply, I thought I had already replied to this lol.
>
>The c key is supposed to cycle through the recipes that are currently displayed so it won't be able to detect recipes from other pages.
>I guess a possible solution for this would be to also add the previous and next page buttons to the c key.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/khanshoaib3/stardew-access/issues/158#issuecomment-1703836488
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

-- 
Sorry about the test, it's just a me thing.
Michael Taboada, Creator of Games. Does that make me a god, well, sorta.
My pgp key: 79BC390E8864CD71305D4DD606CD2197A6EE5ED7
My website: https://michaels.world
2MB website: https://2mb.games
Don't believe everything you read on the internet. I might not be real, you might not be real, and this email certainly isn't real.
Sent from my super powered...
stationary bicycle

**Comment by khanshoaib3** [comment]
@lilmike It should only skip a recipe if it's locked otherwise it should read it.
Maybe send the log but I doubt that there will be anything useful there.

**Comment by khanshoaib3** [comment]
@lilmike This should been fixed now. Can you verify it with the latest beta?
