### ISSUE TITLE
Detect Deconstructor Status

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#166]
Stardew Access doesn't currently detect if the deconstructor is busy or harvestable, making it difficult to know when the machine is finished processing, or indeed that it is occupied.

**Comment by khanshoaib3** [comment]
Patched this in the mentioned commit and from next update if you encounter any machine that doesn't speak it's status, you can try adding the machine's name in the `assets/TileData/trackable_machines.json`.
