### ISSUE TITLE
I've found the Cellar entrance

### ISSUE THREAD

**Issue by fz0308** [khanshoaib3/stardew-access#179]
Hello, I've found the the cellar entrance of  the farm house that has been upgraded 3 times. It's on 4x 25 y to 5x 25 y. Please add it to statictiles.json or something like that because Stardew Access doesn't report it.

**Comment by ParadoxiKat** [comment]
I'll make sure this is properly tracked in the next beta.

**Comment by Bartholomue** [comment]
Unless something dramatic changed in the 1.5X iteration, it is already tracked in the entrances category as far as I'm aware.

**Comment by ParadoxiKat** [comment]
I never upgraded high enough to know if it was or wasn't tracked pre 1.5; it was not tracked when I force upgraded to test it. I've fixed it with the new refactor.
