### ISSUE TITLE
feature request: show quality symbols on in progress casks

### ISSUE THREAD

**Issue by lilmike** [khanshoaib3/stardew-access#189]
Hiya,

According to the wiki, visually casks will show the quality of the item inside, making it possible to decide to take the item out early if it's at a suitable quality. Can this be implemented for stardew access?

Thanks,

-Michael.

**Comment by khanshoaib3** [comment]
Will look into this, thanks.

**Comment by khanshoaib3** [comment]
Well, turns out we can have it speak the details of items inside of any machine. So I did just that, and as such casks and other similar machines should speak the item's details since the next beta.
