### ISSUE TITLE
chests are broken again?

### ISSUE THREAD

**Issue by paxcoder** [khanshoaib3/stardew-access#191]
I compiled Stardew access again today, and, chests are broken? and it says something like: inventory menu item empty
and, I can't see the stuff in the chest.

**Comment by khanshoaib3** [comment]
@paxcoder I just checked and they seem to be fine.

**Comment by ParadoxiKat** [comment]
@paxcoder is this issue still occurring for you?

**Comment by paxcoder** [comment]
Nope, it stopped after re building the thing. Issue may be closed.
