### ISSUE TITLE
sapi support for this mod

### ISSUE THREAD

**Issue by mojsior** [khanshoaib3/stardew-access#3]
Can you add a support for ms sapi as a speech output. It can be usefull if some one doesnt uses nvda or jaws.

**Comment by shoaib11120** [comment]
Yup, I will add that in fututre. Sorry for the late reply, I don't get notification on github for some reason.

**Comment by khanshoaib3** [comment]
So I've implemented [Tolk](https://github.com/ndarilek/tolk) library for windows which supports JAWS, NVDA, and others including SAPI but in my previous testing it didn't worked, I guess the library needs to be updated.
I'll close this issue for now but I will see what I can do to implement sapi later on.
