### ISSUE TITLE
Tile Info Menu

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#30]
With the advent of the tile explorer comes many possibilities. One of them I'd love to see come to fruition is the ability to press Shift + Enter and name the object / tile that the exploration cursor is on. When facing a labeled tile, speak the custom label if it exists. This would go a long ways towards being able to make custom maps and mods playable with some work on the player's part.
In another issue I posted, for example, the mill is just a 4 x 2 block of tiles that say mill. But if we could label the input and output tiles, we could adapt things as we needed. If we see benches and chairs that can be sat on but that aren't named, we could just name them ourselves.

**Comment by khanshoaib3** [comment]
Hmm, this is interesting, I'm thinking of opening a menu when we press shift enter with options like Mark (an alternative to mark command) and add to static tiles json.
I actually thought of an in-game command or something to add new entries to static tiles json.

**Comment by Bartholomue** [comment]
I wonder if it wouldn't be better to add the labels added by this feature request to an additional file like custom-tiles.json? That way the static tiles won't be touched and can always be reverted to simply by deleting the custom definitions.
I do love the idea of being able to mark from the shift + enter command as well.

**Comment by khanshoaib3** [comment]
Was thinking of adding the custom-tiles.json as well

**Comment by khanshoaib3** [comment]
Added custom-tiles.json support b4560bc9e183c2896962be31b0088ae391fbe217

**Comment by khanshoaib3** [comment]
Added in #192
