### ISSUE TITLE
Monster Tools and Info

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#32]
Combat is a pretty iffy prospect with Stardew Access currently. I propose the following changes to help visually impaired players deal with monsters.

Allow players to specify a melee proximity range as well as slingshot proximity range for monsters in the config file.
Play a sound and/or announce the direction of monsters within that proximity range, relevant to the weapon they are wielding.
Allow players to snap to face the closest monster within the proximity range via a configurable button.

**Comment by khanshoaib3** [comment]
Great suggestions, will look into them soon.
