### ISSUE TITLE
Underlying Map-Specific Static Labels

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#41]
If it's at all possible, could we change the "farm" in static-tiles.json to apply to the loaded farm type? "farm_combat" has a different place for the farm cave, for example, as does farm_fourCorners, etc. The current labels only provide for the standard farm, so if there's any way to extrapolate the farm type and use labels accordingly, it would greatly reduce the confusion that might occur when playing on other farm layouts. If it makes it easier, simply copy the current static definitions for the farm into the various farm types, and I'll gladly go through and redefine them as required.

**Comment by Bartholomue** [comment]
Changed the issue title since the ability to define titles based on underlying map is useful in other areas too, such as on the town map. The prime example for the town is whether or not the player takes the Joja path. If a player unlocks the theater under the Joja path, a different map layer is loaded which displays the ticket booth and theater where the community center used to be. Choosing the community center path loads a different underlying map that shows the theater and ticket booth at the abandoned Joja mart.

**Comment by khanshoaib3** [comment]
Patched as of b6b8ad8c8abf905a6f6147f8d92ea628c2f8d0ed
Have also added possibility to add entries specific to town map in joja run but not yet added entries to the static-tiles.json itself. Will look at it later.
