### ISSUE TITLE
Update Buildlist On Load and Wake

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#45]
Would it be possible to have Stardew automatically perform the buildlist function (without the chat display) upon loading a game and waking up at 6 AM? This would auto-update the mod to recognize upgraded buildings, and it would be a quality of life improvement so that you don't have to type /buildlist as often, since you only need to do buildlist on changes.

**Comment by khanshoaib3** [comment]
This is doable, will see

**Comment by khanshoaib3** [comment]
Patched dccbf8b79faf6295207eaa649b36d9adeedadb5b
