### ISSUE TITLE
Treat Caret (^) As Newline

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#46]
Stardew uses the caret symbol in a lot of its text as a line break, but Stardew Access seems to bypass the formatting and just calls them as they are. Take the following secret note:
Someone is ^    waiting for you ^        on level 100 ^         in^          the^             skull cavern...
Without converting the caret symbols to line breaks, it is very cumbersome to read a lot of game text. This shows up on screen (and should be sent to Accessible Output as):
Someone is 
    waiting for you 
        on level 100 
         in
          the
             skull cavern...

**Comment by khanshoaib3** [comment]
Pathced as of 5205df84002667b768df61d533fcddb1fba7fa8c
