### ISSUE TITLE
Emptied Signs Retain Content Description

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#50]
If you remove an object from a sign, Stardew Access still treats the sign as having that object.

**Comment by khanshoaib3** [comment]
I don't think we can remove an object from signs, we can only replace it and to remove it, we have to destroy the sign and place it again. Can you please recheck this issue.
Although i did found and fixed another related bug, thanks :)

**Comment by khanshoaib3** [comment]
I don't think we can remove an object from signs, we can only replace it and to remove it, we have to destroy the sign and place it again. Can you please recheck this issue.
Although i did found and fixed another related bug, thanks :)

**Comment by Bartholomue** [comment]
You can right click on a sign that's holding an object and your character will remove the object from it. This is an innate ability of Stardew -- in fact, it's so easy to remove objects from signs that there are actually mods to prevent the accidental removal of objects from signs.

**Comment by khanshoaib3** [comment]
Huh, I tried that and the object was still present in the sign, I'll recheck.

**Comment by khanshoaib3** [comment]
I still can't recreate this bug, can you post the link to one of those mods please.
