### ISSUE TITLE
Tether Mouse To Tile Exploration

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#53]
Would it be possible to have an option to make the mouse follow the tile exploration keys? It would be really useful in being able to click on distant objects, and it would let sighted assistance see where you're moving the tile view to, say, outline an object size and shape.
It does need to snap back to the player's view once they turn or move, though.

**Comment by khanshoaib3** [comment]
There is an option to that i think, I'll recheck.

**Comment by khanshoaib3** [comment]
@Bartholomue It already does, the game doesn't let us interact with objects that are far.
