### ISSUE TITLE
Bracketed Unique Identifiers For Tile Names

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#54]
Provide a facility to provide a bracketed number in a tile definition that would be silent in Stardew Access name parcing, so that identical tile names can each have their own unique identifier.
Example:
    "Stool[1]": {
      "x": [2],
      "y": [13],
      "type": "furniture"
    },
    "Stool[2]": {
      "x": [11],
      "y": [16],
      "type": "furniture"
    },
    "Stool[3]": {
      "x": [9],
      "y": [17],
      "type": "furniture"
    },
All three entries would show up as just "Stool" in the tile naming, but the bracketed identifier would make each definition unique, thereby addressing the issue whereby multiple similarly named tile definitions are ignored.

**Comment by khanshoaib3** [comment]
patched d131d26ac834d50b7cf9a38fc1d81c77497b6486
