### ISSUE TITLE
Content Pack Definitions

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#55]
Provide a method for users to create content pack tile definitions to develop accessibility for mods they're interested in, or to cover any gaps in the main static definitions.
Map key names should accept a new format like "Town||StardewValleyExpandedCP", where the bit after the two vertical bars is the unique identifier for a mod (as specified in their manifest). The entries in such a key would only apply to the targeted map if the appropriate mod is detected.

**Comment by khanshoaib3** [comment]
Patched 1187ba30e7103449b5c672fc594ac39499c2229a Look here for example https://github.com/khanshoaib3/stardew-access/blob/1187ba30e7103449b5c672fc594ac39499c2229a/stardew-access/Features/StaticTiles.cs#L59-L77
