### ISSUE TITLE
Announce Additional Currencies

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#56]
Could we get a bindable key (default Shift + R) to announce other kinds of currency? If a currency is null or 0, ignore it.
Currencies include: Festival score, Qi coins, golden walnuts, Qi gems.

**Comment by khanshoaib3** [comment]
Patched 950ab21d61ca1cc51edbcc8aef174ea6cabec036 To speak other currencies open the inventory page and press the money key (default to R)
