### ISSUE TITLE
Verbose Inventory Option

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#59]
While I like the new guidance system that tells a player if an item is useable at the current location, I'm also a more advanced player who knows when items are usable already. Can this feature please be made configurable in the config file? Furthermore, can it be made to play small audio prompt sounds rather than speaking "not usable here"? It makes navigating the inventory much more verbose than it has to be to have that phrase attached to every object that Stardew Access deems unapplicable.

**Comment by khanshoaib3** [comment]
That's a great suggestion, I'll see what I can do, thanks.

**Comment by khanshoaib3** [comment]
Patched in #87
