### ISSUE TITLE
[Tile Explorer] Announce Farmer Name

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#63]
While exploring tiles with the tile explorer, arrowing across the tile where the farmer is standing says empty, misleadingly reflecting that nothing is at that location. Would it be possible to announce the farmer's name at the location where the title explorer is?

**Comment by khanshoaib3** [comment]
Patched 7a4ca8983625fc0ebb13f54953d8f5bef89c1481
