### ISSUE TITLE
Chests To Containers

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#64]
Rename the Chests category to Containers so that it can be a wider catch-all for container objects on the maps such as dumpsters, trash cans, etc. Right now it only shows chests, and while that's useful, I feel that it could be better applied for more organization so that things aren't just all piled in to interactable or other.

**Comment by khanshoaib3** [comment]
Patched 657f5cc884693147594e842943c9b1c109747ef0

**Comment by khanshoaib3** [comment]
Patched f5db6eb655e1338f13091ab6f14880fb151b98e5
