### ISSUE TITLE
Custom Tiles Duplicate Definitions

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#70]
I did a test by redefining the lumber pile on the farm in the custom tiles file to move it down 2 tiles to 16y. Upon looking at the tile explorer, Stardew Access is defining both what's in the custom tiles file and what's in static tiles, rather than overriding static tiles with custom tiles. I now have lumber pile both at 14y (the location in static tiles) and at 16y (as defined in custom tiles).

**Comment by Bartholomue** [comment]
To further expand on this, here's how I think the prioritization should work:
1. If a location name exists in both custom tiles and static tiles, discard the entire location key. This means someone defining a custom tiles change for a location would have to copy over the whole location key to their custom tiles file, but it also provides much more flexibility and less redundancy since, usually when a location is being redefined, multiple tile locations have changed. Trying to keep both the static tiles and custom tiles definitions just leaves room for redundancy errors.
2. If a location name like "town" exists, but also "town||FlashShifter.StardewValleyExpandedCP" exists, discard the iteration without the mod specifier if the mod is detected. If the mod is not detected, discard the mod specific key and revert to the version without the mod specification. In both cases, custom tiles definitions should always take precedence and discard static tiles, so that if custom tiles has "town" and "town||FlashShifter.StardewValleyExpandedCP", then the CP token would take precedence over the regular town location definition in custom tiles... and that "town" definition in custom tiles would take precedence over static tiles. If "town" doesn't exist in custom tiles, then of course fall back to static tiles.

**Comment by khanshoaib3** [comment]
@Bartholomue discarding entire location in both cases would also mean that you will have to copy all the necessary entries from the static tiles.
