### ISSUE TITLE
NVDA not detected with Stardew Access 1.3.3

### ISSUE THREAD

**Issue by fz0308** [khanshoaib3/stardew-access#71]
Hello, I want to report an issue with Stardew Access 1.3.3. After I install it my NVDA can't read the game screen anymore. And when i check smapi console, there is a message says no screen reader detected. Please fix this issue. Thanks before

**Comment by mojsior** [comment]
Copy nvda controller client from stardew access directory to main stardew valley directory. This way is working for me
