### ISSUE TITLE
Bulletin Board Offset

### ISSUE THREAD

**Issue by Bartholomue** [khanshoaib3/stardew-access#72]
Consider offsetting the tile of the bulletin board bundle in the community center by +1 on the Y axis so that it becomes the edge of the object, rather than the center. Accessible Tiles has issues tracking and pathing to the bulletin board bundle as it's currently defined, since it's technically blocked by an obstacle. Moving the tile definition down by 1 should alleviate this issue.

**Comment by khanshoaib3** [comment]
Patched 871c0b47cb9d5b58ac6078025a2b9dd8a9398ba2
