### ISSUE TITLE
error freezing on stardew access

### ISSUE THREAD

**Issue by xethea16** [khanshoaib3/stardew-access#74]
Hello, I am having problems with the mod currently.

When I go into the mines and after fighting off monsters, the mod will freeze and won't be able to locate the next object or character. I press the home button to get where the object is, but nothing happens and no information is given. 
My friend says there is an error all in red in smapi. I took all mods out except for accessible tiles, console commands, error handler, save backup, stardew-access, stardew hack, chest anywhere and fishing assistant mod. May someone please help me or try to offer a solution? Thank you.

**Comment by khanshoaib3** [comment]
@xethea16 sorry for the late reply but what version of stardew valley area you running?? And send the log file as well, it'll help debug it faster :)

**Comment by xethea16** [comment]
hello, I was able to figure it out, it was a mod I had that was conflicting with accessible tiles. Thank you for your help though.

**Comment by khanshoaib3** [comment]
Oh, awesome, glad it's fixed and btw which mod was it??
