### ISSUE TITLE
Some tile's name will fallback to english

### ISSUE THREAD

**Issue by PaienNate** [khanshoaib3/stardew-access#78]
Seems some tile's name will fallback to english when using other language, for example, when the arrow points to bed, it will Say "床" in chinese as well, but when points to the chest it will say "Chest" not its name in chinese. I guess, maybe these things have their name but player will never see this (Like "FarmHouse Door") , so maybe they ignore to translate it?
If so, is there anyway to add these translate?

**Comment by khanshoaib3** [comment]
Will look into it, I think we'll have to add custom translations for these times unless they're added into the game itself.

**Comment by ParadoxiKat** [comment]
@khanshoaib3 should we close this as resolved by fluent integration in v1.5.0? Obviously the translations themselves have to be created but this is now an issue of those mods completion rather than stardew-access' functionality.

**Comment by khanshoaib3** [comment]
Yup, we should 🙂
