### ISSUE TITLE
Speech interrupt then no speech issue on 1.5.6

### ISSUE THREAD

**Issue by celtichawk** [khanshoaib3/stardew-access#93]
This has just happened on the latest release, running Stardew Valley 1.5.6 with the latest Smapi and release of Stardew Access on my Arch Linux machine.

Initially, it all seems to load up fine, I get the usual SMAPI messages, the mod is found,  and I hear load button, but after that, nothing at all. Moving around does nothing, and clicking does nothing as well in terms of speech.

Toggling TTS in SMAPI does nothing at all as well. Where would I find the log file to see what's going on? I followed the install instructions and put the Linux files where it said to.I had it working before, but now on a fresh Arch install, zero luck, it is acting as soon as I press a button, the speech dies.

The only thing I am seeing in Smapi console is that speech interrupt is happening, but I am not sure why that would kill the whole speech system, right after it starts up correctly?

**Comment by khanshoaib3** [comment]
Sorry for the late reply,
here's the location for the log file - `~/.config/StardewValley/ErrorLogs`. You can also upload it to the smapi log parser - [here](https://smapi.io/log)

In my experience, I had issues with setting up screen reader in arch linux. But I'm not really a screen reader user, so I'm not sure if it's arch specific.

**Comment by khanshoaib3** [comment]
@celtichawk any update?
