### ISSUE TITLE
General Mod Config Menu

### ISSUE THREAD

**Issue by veer358** [khanshoaib3/stardew-access#97]
Thank you so much for creating this mod!! I was wondering if you're planning on connecting it with "General Mod Config Menu" so we can change the settings in game? Or somehow making it possible to edit the settings while the game is open? I find it a bit difficult to change the keybinds and having to open the game and close it whenever I wanna test or adjust something in fear of somehow breaking the game if I'd changed it while the game is open. (I'm deeply sorry, I don't know much about modding and such)
If you're not planning to do that, thank you for your time! I'm so grateful for this mod either way! /gen

**Comment by khanshoaib3** [comment]
I am actually working on GMCM, here's my fork - [spacechase0-stardew-valley-mods](https://github.com/khanshoaib3/spacechase0-stardew-valley-mods). I just started working on this so only the mod configs list menu is somewhat accessible right now. Will update on the progress.
